# application.yml
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: yeet-online
  datasource:
    url: jdbc:h2:./db/database
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration
    fail-on-missing-locations: true
