# application.yml
spring:
  application:
    name: yeet-online
  datasource:
    url: jdbc:h2:./database
    driver-class-name: org.h2.Driver
  flyway:
    locations: classpath:db/migration
    fail-on-missing-locations: true
